### ISSUE TITLE
OSError on while adding concise_concepts to spacy nlp pipeline

### ISSUE THREAD

**Issue by mithrepo** [Pandora-Intelligence/concise-concepts#22]
Hi Team,
I am getting below issue while adding concise_concepts to spacy nlp pipeline in the latest version

**nlp.add_pipe("concise_concepts", config={"data" : prints_data})** 

2022-10-11 16:25:18.181 ISTextract_expertreports_printsdu74r1dm4mrf ERROR:root:Traceback (most recent call last): File "/workspace/main.py", line 12, in wrapper response = wrapped_func(*args, **kwargs) File "/workspace/main.py", line 43, in extract_expertreports_prints output_result = extract_prints(year) File "/workspace/extractprints_frompdf.py", line 65, in extract_prints nlp.add_pipe("concise_concepts", config={"data" : prints_data}) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/spacy/language.py", line 792, in add_pipe pipe_component = self.create_pipe( File "/layers/google.python.pip/pip/lib/python3.8/site-packages/spacy/language.py", line 674, in create_pipe resolved = registry.resolve(cfg, validate=validate) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/thinc/config.py", line 746, in resolve resolved, _ = cls._make( File "/layers/google.python.pip/pip/lib/python3.8/site-packages/thinc/config.py", line 795, in _make filled, _, resolved = cls._fill( File "/layers/google.python.pip/pip/lib/python3.8/site-packages/thinc/config.py", line 867, in _fill getter_result = getter(*args, **kwargs) File "/layers/google.python.pip/pip/lib/python3.8/site-packages/concise_concepts/__init__.py", line 51, in make_concise_concepts return Conceptualizer( File "/layers/google.python.pip/pip/lib/python3.8/site-packages/concise_concepts/conceptualizer/Conceptualizer.py", line 101, in __init__ self.run() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/concise_concepts/conceptualizer/Conceptualizer.py", line 117, in run self.create_conceptual_patterns() File "/layers/google.python.pip/pip/lib/python3.8/site-packages/concise_concepts/conceptualizer/Conceptualizer.py", line 409, in create_conceptual_patterns with open(self.json_path, "w") as f: OSError: [Errno 30] Read-only file system: './matching_patterns.json

**Comment by B-Abbasi** [comment]
Are you able to run the simple example given in documentation?
